# Car Price Prediction - TASK #03

### Importing Libraries

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

### Information about data

In [2]:
df = pd.read_csv("./CarPrice_Assignment.csv")

In [3]:
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [4]:
df.tail()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [5]:
df.sample(5)

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
9,10,0,audi 5000s (diesel),gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.00,160,5500,16,22,17859.167
134,135,3,saab 99le,gas,std,two,hatchback,fwd,front,99.1,...,121,mpfi,2.54,2.07,9.30,110,5250,21,28,15040.000
21,22,1,dodge rampage,gas,std,two,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.41,68,5500,37,41,5572.000
48,49,0,jaguar xf,gas,std,four,sedan,rwd,front,113.0,...,258,mpfi,3.63,4.17,8.10,176,4750,15,19,35550.000
69,70,0,buick century,diesel,turbo,two,hardtop,rwd,front,106.7,...,183,idi,3.58,3.64,21.50,123,4350,22,25,28176.000

### Data Preprocessing

In [6]:
# taking only required columns
df = df[['enginesize','carlength','carwidth','carheight','curbweight','wheelbase','stroke','horsepower','compressionratio','highwaympg','peakrpm','citympg','price']]

In [7]:
df.sample(5)

,enginesize,carlength,carwidth,carheight,curbweight,wheelbase,stroke,horsepower,compressionratio,highwaympg,peakrpm,citympg,price
36,92,157.1,63.9,58.3,2024,96.5,3.41,76,9.2,34,6000,30,7295.0
101,181,181.7,66.5,55.1,3095,100.4,3.27,152,9.0,22,5200,17,13499.0
180,171,187.8,66.5,54.1,3131,104.5,3.35,156,9.2,24,5200,20,15690.0
65,140,175.0,66.1,54.4,2670,104.9,3.16,120,8.0,27,5000,19,18280.0
120,90,157.3,63.8,50.6,1967,93.7,3.23,68,9.4,38,5500,31,6229.0

In [8]:
df.isna().sum()

enginesize          0
carlength           0
carwidth            0
carheight           0
curbweight          0
wheelbase           0
stroke              0
horsepower          0
compressionratio    0
highwaympg          0
peakrpm             0
citympg             0
price               0
dtype: int64

Our data has no null values

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   enginesize        205 non-null    int64
 1   carlength         205 non-null    float64
 2   carwidth          205 non-null    float64
 3   carheight         205 non-null    float64
 4   curbweight        205 non-null    int64
 5   wheelbase         205 non-null    float64
 6   stroke            205 non-null    float64
 7   horsepower        205 non-null    int64
 8   compressionratio  205 non-null    float64
 9   highwaympg        205 non-null    int64
 10  peakrpm           205 non-null    int64
 11  citympg           205 non-null    int64
 12  price             205 non-null    float64
dtypes: float64(7), int64(6)
memory usage: 20.9 KB

In [10]:
df.describe()

,enginesize,carlength,carwidth,carheight,curbweight,wheelbase,stroke,horsepower,compressionratio,highwaympg,peakrpm,citympg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,126.907317,174.049268,65.907805,53.724878,2555.565854,98.756585,3.255415,104.117073,10.142537,30.751220,5125.121951,25.219512,13276.710571
std,41.642693,12.337289,2.145204,2.443522,520.680204,6.021776,0.313597,39.544167,3.972040,6.886443,476.985643,6.542142,7988.852332
min,61.000000,141.100000,60.300000,47.800000,1488.000000,86.600000,2.070000,48.000000,7.000000,16.000000,4150.000000,13.000000,5118.000000
25%,97.000000,166.300000,64.100000,52.000000,2145.000000,94.500000,3.110000,70.000000,8.600000,25.000000,4800.000000,19.000000,7788.000000
50%,120.000000,173.200000,65.500000,54.100000,2414.000000,97.000000,3.290000,95.000000,9.000000,30.000000,5200.000000,24.000000,10295.000000
75%,141.000000,183.100000,66.900000,55.500000,2935.000000,102.400000,3.410000,116.000000,9.400000,34.000000,5500.000000,30.000000,16503.000000
max,326.000000,208.100000,72.300000,59.800000,4066.000000,120.900000,4.170000,288.000000,23.000000,54.000000,6600.000000,49.000000,45400.000000

### Train Test Split

In [11]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=3)

### Training Model

In [13]:
model = LinearRegression()
model.fit(X=X_train,y=y_train)

LinearRegression()

### Prediction

In [14]:
y_pred = model.predict(X_test)

In [15]:
r2_score(y_test,y_pred)

0.8301682522378183

According to score our model is perfoming preety good :)